### ISSUE TITLE
Add missing details in KMG explanation

### ISSUE THREAD

**Issue by jellevos** [dwh-outsite/outsite.nl#50]
- 8 weeks
- Thursday 20:00

**Comment by BoukeStoelinga** [comment]
Singup form for the kmg: Add a box for main language (English/Dutch)

Kmg dinner signup form. We want something that is visible to only kmg members. Options for being the cook, vega, etc. Prefably visible to all kmg members, so they can see who is joining dinner, who is cooking and who is a vegetarian.
