### ISSUE TITLE
Consider showing Instagram feed

### ISSUE THREAD

**Issue by jellevos** [dwh-outsite/outsite.nl#55]

**Comment by casperboone** [comment]
I considered this while building the site, however, after looking at our insta feed I decided not to show this. The content simply does not seem relevant to show at this time. This might change in the future ofc.

![image](https://user-images.githubusercontent.com/15815208/62983722-b7a0ff00-be30-11e9-9e8c-cdc5f8ad140e.png)

**Comment by casperboone** [comment]
Closing this issue (see above), feel free to re-open.
